#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    background = "dark"
    automatic_update = 1
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_vimfiler_filetypeicon = true
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    # Show vimfiler on left
    filetree_direction = "left"
    #enable_vimfiler_gitstatus = true
    enable_tabline_filetype_icon = true
    #statusline_unicode_symbols = 0
    vimfiler_print_filename = true
    search_highlight_persist = true
    # Tagbar stuff
    tagbar_show_visibility = true
    tagbar_show_linenumbers = 1
    # GitHub stuff
    github_username = "mertyildiran"
    bootstrap_before = "myspacevim#before"
    # Disabled plugins
    disabled_plugins = ['phpfold.vim']
    guifont = "Menlo, Consolas, DejaVu Sans Mono, monospace"


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-delay = 3
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 12

[[layers]]
name = 'colorscheme'
enable = true

[[layers]]
name = 'ctrlp'
enable = true

[[layers]]
name = 'lang#c'
enable = true

[[layers]]
name = 'lang#csharp'
enable = true

[[layers]]
name = 'lang#elixir'
enable = true

[[layers]]
name = 'lang#go'
enable = true

[[layers]]
name = 'lang#haskell'
enable = true

[[layers]]
name = 'lang#html'
enable = true

[[layers]]
name = 'lang#java'
enable = true

[[layers]]
name = 'lang#javascript'
enable_flow_syntax = true
enable = true

[[layers]]
name = 'lang#lisp'
enable = true

[[layers]]
name = 'lang#markdown'
enable = true

[[layers]]
name = 'lang#ocaml'
enable = true

# Disable folding: set nofoldenable
[[layers]]
name = 'lang#php'
enable = true

[[layers]]
name = 'lang#python'
format-on-save = 1
enable = true

[[layers]]
name = 'lang#ruby'
enable = true

[[layers]]
name = 'lang#typescript'
enable = true

[[layers]]
name = 'lang#vim'
enable = true

# Install GNU Global: apt install global
[[layers]]
name = "tags"
enable = true

# https://github.com/idanarye/vim-vebugger
[[layers]]
name = "debug"
enable = true

# For outline: apt install exuberant-ctags
[[layers]]
name = 'ui'
enable = true

[[layers]]
name = 'git'
enable = true

[[layers]]
name = 'github'
enable = true

[[layers]]
name = "VersionControl"
enable = true

[[layers]]
name = 'unite'
enable = true

[[layers]]
name = "tmux"
enable = true

[[layers]]
name = "default"
enable = true

[[custom_plugins]]
name = 'wakatime/vim-wakatime'
merged = 0

[[custom_plugins]]
name = 'ryanoasis/vim-devicons'
merged = 0

[[custom_plugins]]
name = 'jwalton512/vim-blade'
merged = 0

[[custom_plugins]]
name = 'lilydjwg/colorizer'
merged = 0
on_cmd = ['ColorHighlight']
